export const APCourses = ["Studio Art Drawing", 
                    "Studio Art 2D Art and Design",
                    "Studio Art 3D Art and Design",
                    "Art History",
                    "Biology",
                    "Chemistry",
                    "Computer Science A",
                    "Computer Science Principles",
                    "Microeconomics",
                    "Macroeconomics",
                    "English Literature and Composition",
                    "English Language and Composition",
                    "Enviornmental Science",
                    "Government and Politics: United States",
                    "Government and Politics: Comparative",
                    "History: United States",
                    "History: European",
                    "History: World",
                    "Human Geography",
                    "Chinese",
                    "French",
                    "German",
                    "Italian",
                    "Japanese",
                    "Spanish Language and Culture",
                    "Latin: Literature",
                    "Latin: Virgil",
                    "Spanish Literature and Culture",
                    "Calculus AB",
                    "Calculus BC",
                    "Music Theory",
                    "Physics 1",
                    "Physics 2",
                    "Physics C Mechanics",
                    "Physics C Electricity and Magnetism",
                    "Psychology",
                    "Statistics",
                    "African American Studies"];

export const IBCourses = ["Anthropology", "Biology", "Business and Management", "Chemistry", 
    "Computer Science", "Dance", "Economics", "English", "Film", "Geography", 
    "Global Politics", "History of Africa", "History of the Americas", 
    "History of Asia and Oceania", "Twentieth-Century World History", 
    "History of Europe and the Middle East", "History of Europe and the Islamic World",
    "Language B", "Latin", "Linguistics", "Language A", "Mathematics: Applications and Interpretations",
    "Mathematics: Analysis and Approaches", "Music", "Philosophy", "Physics", "Psychology",
    "Theatre Arts", "Visual Arts"]